name: GitHub Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ray
          template: classic
          base: header, activity, community, repositories, metadata
          config_theme: dark
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_isocalendar: yes
          plugin_stargazers: yes
          plugin_activity: yes
